# Generated by Django 3.1.2 on 2021-05-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followed_cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.DeleteModel(
            name='Citi',
        ),
    ]
