# Generated by Django 3.1.2 on 2021-05-03 22:46

from django.db import migrations
from django.utils import timezone


def create_crone_task(apps, schema_editor):
    from django_q.models import Schedule

    Schedule.objects.create(
        func='weatherwoman.tasks.order_mails_to_sent',
        schedule_type=Schedule.DAILY, next_run=timezone.now().replace(hour=8, minute=0),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('django_q', '0013_task_attempt_count'),
    ]

    operations = [
        migrations.RunPython(create_crone_task)
    ]
